# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_

  - interaction: vrchat_with_curiosity_image_ppo_agent
  - data_collectors: image_dynamics_ppo
  - models: i_jepa_sioconv_resnetpolicy_small
  - trainers: i_jepa_forward_dynamics_ppo
  - threads: default

  - checkpointing: default
  - devices: cuda
  - paths: default
  - hydra: default

  # You can specify configuration values that are shared among all config files.
  - shared: default

  # experiment configs allow for version control of specific hyperparameters
  - experiment: null

task_name: default

# You can specify saved checkpoint path when system is begun.
saved_checkpoint_path: null

# You can specify `hydra.job_logging.root.level`
log_level: INFO

# You can specify the time scale for the experiment.
time_scale: 1.0

max_uptime: inf # This value will scale by `time_scale`.

torch_float32_matmul_precision: "high" # Using tensor core.
